name: Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/private.key
        chmod 600 ~/.ssh/private.key
        echo -e "Host ec2\n\tHostName ${{ secrets.EC2_HOST }}\n\tUser ${{ secrets.EC2_USER }}\n\tIdentityFile ~/.ssh/private.key\n\tStrictHostKeyChecking no" > ~/.ssh/config
        
    - name: Deploy to EC2
      run: |
        # Create deployment script
        cat > deploy.sh << 'EOL'
        #!/bin/bash
        cd /home/${{ secrets.EC2_USER }}/app
        git pull origin main
        
        # Activate virtual environment
        source /home/${{ secrets.EC2_USER }}/app/venv/bin/activate
        
        # Install dependencies
        pip install -r requirements.txt
        
        # Restart the application
        sudo systemctl restart afcon-chatbot
        EOL
        
        # Copy deployment script to EC2
        scp deploy.sh ec2:~/deploy.sh
        
        # Execute deployment script on EC2
        ssh ec2 "chmod +x ~/deploy.sh && ~/deploy.sh" 